### ISSUE TITLE
Error handling in the sendTransaction function

### ISSUE THREAD

**Issue by jinoosss** [gnolang/tm2-js-client#46]
Currently, providers only validate for success/failure of calls in general.
However, when we call broadcast_tx of the sendTransaction function, 
we can get an error about the transaction as a response.
This error cannot be checked in the block, so I think error handling is necessary.

@zivkovicmilos  I have a few questions.
1. Is it intended that when a transaction error occurs, a hash is the response?
2. Do you think tm2-js-client should handle gno's errors?
(If we use the gno response as is, the error types need to be checked in the gno repository and handled)
** gno errors: https://github.com/gnolang/gno/blob/0b38c8d793f83d50929ca27351f2b3cb89e9b974/tm2/pkg/std/errors.go

**Comment by zivkovicmilos** [comment]
Hey @jinoosss,

Thank you for opening up the issue, these are completely valid questions 🙏 

I definitely believe the transaction send method definitely _should_ alert of any errors that occurred during broadcast.
This is probably an oversight on my part when I was implementing it, as the hash information is the only one you'd need for the happy path of sending a transaction (and obvious axios errors are handled by the `RestService`)

As for the error handling, I'm not sure there are any Gno-specific errors, all of these seem to be TM2 related. Am I wrong here?
In any case, the tm2 package should handle tm2 errors, and the gno package should be able to handle gno-specific errors

I will look into adding this functionality soon, or we can coordinate together if you'd like to take a go at it 💪

**Comment by jinoosss** [comment]
Thanks for the comment.

I'd be pleased to coordinate with you.
And I agree with your comments.

Do you have a way of handling TM2 errors in mind?

I personally thought about throwing an error (based on the TM2 response error type).
What do you think about this idea?

**Comment by zivkovicmilos** [comment]
Hey @jinoosss,

Sorry for the somewhat late reply on this issue. I like the idea of throwing an error, I think it's one of the most cleanest ones and doesn't change the API drastically

I need to look into how these errors are returned to clients, as I suspect they're being encoded in amino (we might need to proto them out into a JS type). I'll open a draft PR and add you to get your opinion on changes 🙏

**Comment by zivkovicmilos** [comment]
I've opened up a small PR to address point 1:

https://github.com/gnolang/tm2-js-client/pull/59

Please let me know what you think 🙏

**Comment by jinoosss** [comment]
@zivkovicmilos,  
Thanks for identifying the problem 🙏

I think it's a good idea to throw a clear error so that it can be used without knowing the core of the chain.
I think it would be more useful to make it so that you only need to know tm2-js-client to handle the error.

I'll take a closer look at the PR you suggested and offer further comments.

**Comment by jaekwon** [comment]
BTW please take a look at the comments in tm2/pkg/bft/rpc/core/mempool.go for details of response format for broadcast_tx_* calls.

> broadcast_tx_commit waits for the transaction to be committed to a block before returning the response to the client. At this point, the transaction is actually _simulated_, and it would error out potentially if the tx messages are not valid.

It runs the tx in a cachewrapped context so that all the changes can be discarded if there is an error during execution (delivertx). But for clarity I think we should not call this "simulation" since it does write if the tx succeeds, and also baseapp.Simulate() is an existing function which works similarly, except it *always* discards the result.

(if we wanted, we could consider exposing a "simulate" RPC endpoint, but I think that's outside the scope of this issue, and also we'd have to figure out how to throttle it somehow.)

> This is the least favorable endpoint to use for clients, because it blocks the client response until a transaction (if ever) is committed to a block in the chain.

broadcast_tx_commit isn't the best for production usage because it runs a redundant checktx step. That is, it first runs checktx, and if that succeeds, then runs delivertx, but that means the ante handler is run twice.

(I think we could just modify broadcast_tx_commit to make the checktx step optional, if I'm not mistaken. Also we can take a look at tm1 or comet to see what they do.)

But in order to get the actual result value, of course we do have to wait until the block commits (since the result can depend on prior txs). So I'm not sure it's "unfavorable" unless you have a series of txs to commit at once. 

If you don't want to make a blocking rpc request like broadcast_tx_commit, then as per the comments in mempool.go you can listen to the websocket for events. If it is not acceptable to lose results upon websocket failure (since reconnecting the websocket doesn't replay old events) then we should use the event store system which is specifically for replaying the same events as the websocket (and the external indexer should use this because indexing requires impotency and thus requires event replay from last height known by the indexer).

(do we have a PR for that? I remember discussing this months ago but don't recall seeing the code for it)

> Support transaction receipts (or some notion of it) on gno

The transaction receipt is already passed to tm2 as follows:
 1. sdk.Result from handler.Process (from delivertx, which includes the ante handler error if any)
 2. abci.ResponseDeliverTx (wire format from abci-app to tm2)
 3. bft.ABCIResult (tm2 stores the results from ABCI)

All deterministic receipt information should go in all three structures... for example, tx events from the app (in the case of gno.land, these are events published via gno function calls like std.Emit() perhaps. 

> you'd expose an endpoint similar to Ethereum's eth_getTransactionReceipt

The results are available from the "block_results" ABCI call, but this isn't the best way to get the result of a tx based on its hash. The right rpc endpoint for that is "tx", but it is currently commented out (see tm2/pkg/bft/rpc/core/tx.go) because the tx_indexer logic was removed. 

Has there been any work on the replayable event store and external tx indexer? Maybe the external tx index is what should ultimately serve results from tx hashes. This rpc endpoint would arguably get hammered by user clients, so it might make sense to offload that into the external tx indexer which can solve for throughput, rather than requiring a cluster of tm2 nodes to do the same.

----------

See also https://github.com/gnolang/gno/issues/968

**Comment by zivkovicmilos** [comment]
@jaekwon 
>Has there been any work on the replayable event store and external tx indexer? Maybe the external tx index is what should ultimately serve results from tx hashes. This rpc endpoint would arguably get hammered by user clients, so it might make sense to offload that into the external tx indexer which can solve for throughput, rather than requiring a cluster of tm2 nodes to do the same.

Based on our discussions on https://github.com/gnolang/gno/pull/546, there is work being done on two fronts:
- enable event dumps that can be read from a separate process (this is contained in https://github.com/gnolang/gno/pull/546; waiting on your additional comment resolves)
- create a separate tool that can be run to index a chain, and be queriable from clients such as this JS library (but also tools like block indexers etc). Work on this tool will begin as soon as we have https://github.com/gnolang/gno/pull/546 merged, as the parsing logic is highly dependent on reading those saved events. I will open up a new tool repo, and ping you as soon as we complete this scope of work
